version: '3'

services:
  app:
    build:
      context: ./project/app
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - './project/app:/usr/app'
    depends_on:
      - db
  db:
    build: ./project/db/.
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
