CREATE ROLE boiler_user WITH LOGIN ENCRYPTED PASSWORD 'dev_admin';
ALTER ROLE boiler_user CREATEDB;
CREATE DATABASE boiler;
GRANT ALL PRIVILEGES ON DATABASE boiler TO boiler_user;
SET TIME ZONE 'UTC';
